name: Auto Update VOD Source
on:
  schedule:
    - cron: '0 22 * * *' # 北京时间每天早上 6 点自动更新
  workflow_dispatch: # 支持在 GitHub 页面手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Clean Script
        run: python clean_vod.py

      - name: Commit and Push
        run: |
          git config --global user.name "Actions-Bot"
          git config --global user.email "actions@github.com"
          git add my_vod.json
          git commit -m "Updated at $(date)" || exit 0
          git push
